<?php

/**
* Implements hook_theme().
*/
function islandora_riprap_theme($existing, $type, $theme, $path) {
 return [
    'islandora_riprap_summary' => [
      'variables' => ['content' => null, 'outcome' => null, 'mid' => null],
    ],
    'islandora_riprap_report' => [
      'variables' => ['report' => null, 'mid' => null],
    ],
  ];
}

/**
* Default preprocessor function for the islandora_riprap_theme hook.
*/
function template_preprocess_islandora_riprap_report(&$variables) {
  $variables['attributes'] = [
    'id' => ['islandora_riprap_report'],
  ];
}

/**
* Default preprocessor function for the islandora_riprap_theme hook.
*/
function template_preprocess_islandora_riprap_summary(&$variables) {
  $variables['attributes'] = [
    'class' => [$variables['outcome']],
  ];
}

/**
* Implements hook_page_attachments().
*/
function islandora_riprap_page_attachments(array &$attachments) {
  $current_path = \Drupal::service('path.current')->getPath();
  $path_args = explode('/', $current_path);
  // E.g., the Manage Media View for each Islandora object.
  if ($path_args[1] == 'node' && $path_args[3] == 'media') {
    $attachments['#attached']['library'][] = 'islandora_riprap/islandora_riprap';
  }
}
